# Generated by Django 2.2.5 on 2019-11-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventTopic', models.CharField(max_length=500)),
                ('eventDate', models.DateField()),
                ('eventVenue', models.CharField(max_length=500)),
                ('eventOrganizer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speakerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('emailId', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField()),
                ('presentationStyleAverage', models.IntegerField()),
                ('qualityOfContentAverage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantFullName', models.CharField(max_length=255)),
                ('participantIdentifier', models.CharField(max_length=50)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Event')),
                ('speakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Speaker')),
            ],
        ),
    ]
