# Generated by Django 2.2.5 on 2019-11-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventTopic', models.CharField(max_length=500)),
                ('eventDate', models.DateField()),
                ('eventVenue', models.CharField(max_length=500)),
                ('eventOrganizer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speakerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('emailId', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField(blank=True, default='')),
                ('presentationStyleAverage', models.IntegerField(blank=True, default=-1)),
                ('qualityOfContentAverage', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakersForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerTopic', models.CharField(default='', max_length=255)),
                ('speakerSequence', models.IntegerField()),
                ('pollingEnabled', models.BooleanField(default=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Event')),
                ('speakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerFeedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('presentationStyle', models.IntegerField(default='-1')),
                ('contentRelevance', models.IntegerField(default='-1')),
                ('wentWell', models.CharField(blank=True, default='', max_length=1000)),
                ('couldBeBetter', models.CharField(blank=True, default='', max_length=1000)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Event')),
                ('speakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Speaker')),
            ],
        ),
    ]
