# Generated by Django 2.2.5 on 2019-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='presentationStyleAverage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='qualityOfContentAverage',
            field=models.IntegerField(blank=True),
        ),
    ]
