# Generated by Django 2.2.5 on 2019-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerfeedback',
            name='contentRelevance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='speakerfeedback',
            name='presentationStyle',
            field=models.IntegerField(),
        ),
    ]
