# Generated by Django 2.2.5 on 2019-11-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0002_auto_20191125_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('participantFullName', models.CharField(max_length=100)),
                ('participantIdEmail', models.EmailField(max_length=254)),
                ('participantMobile', models.CharField(max_length=15)),
                ('contentQuality', models.IntegerField()),
                ('contentRelevance', models.IntegerField()),
                ('overallExperience', models.IntegerField()),
                ('referenceable', models.BooleanField()),
                ('likedMost', models.CharField(blank=True, default='', max_length=1000)),
                ('couldBeBetter', models.CharField(blank=True, default='', max_length=1000)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_app.Event')),
            ],
        ),
    ]
