# Generated by Django 2.2.5 on 2019-11-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0002_auto_20191121_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='presentationStyleAverage',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='qualityOfContentAverage',
        ),
    ]
