# Generated by Django 2.2.5 on 2019-12-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0003_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventEnable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='eventFeedackEnable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
