# Generated by Django 2.2.5 on 2019-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0003_auto_20191121_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='linkedIn',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='presentationStyleAverage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='qualityOfContentAverage',
            field=models.IntegerField(null=True),
        ),
    ]
