# Generated by Django 2.2.5 on 2019-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0004_auto_20191201_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='clientIp',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='speakerfeedback',
            name='clientIp',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
