# Generated by Django 2.2.5 on 2019-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_app', '0004_auto_20191121_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='linkedIn',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='presentationStyleAverage',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='qualityOfContentAverage',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
